### ISSUE TITLE
Rework pause/un-pause

### ISSUE THREAD

**Issue by ntpincus** [UCSB-CS56-Projects/cs56-android-games-pacman#10]
If the user long swipes or holds their finger down for any extent of time the game will pause. An added pause button would allow the user to control Pacman however they like without accidentally pausing the game.

**Comment by colerogers** [comment]
100 pts

**Comment by jimmylle** [comment]
F16 OK (100 pts)

**Comment by Tektonbuilds** [comment]
The pause button works as it should
