### ISSUE TITLE
Add level selector in Settings Page

### ISSUE THREAD

**Issue by kevinchanucsb** [UCSB-CS56-Projects/cs56-android-games-pacman#13]
In settings page, add a level selector that allows you to change the map used in the DrawingView class. Difficulty changes with more/less pellets, as well as the speed of the overall game.

**Comment by jimmylle** [comment]
This is resolved with these classes: [SettingsActivity](https://github.com/UCSB-CS56-Projects/cs56-android-games-pacman/blob/master/app/src/main/java/com/example/jimmyle/pacmanandroid/SettingsActivity.java) and [LevelGenerator](https://github.com/UCSB-CS56-Projects/cs56-android-games-pacman/blob/master/app/src/main/java/com/example/jimmyle/pacmanandroid/LevelGenerator.java).
