### ISSUE TITLE
Add new Ghosts

### ISSUE THREAD

**Issue by kevinchanucsb** [UCSB-CS56-Projects/cs56-android-games-pacman#15]
Add new ghosts from Ghosts.java and change the Movement class to have static methods to move the Ghost and Pacman

**Comment by colerogers** [comment]
200 pts

**Comment by jimmylle** [comment]
F16 OK (200 pts)

**Comment by Tektonbuilds** [comment]
The ghost AIs will be in the same position if they stack. That should be a separate issue.
