### ISSUE TITLE
Pacman and Ghost Collision

### ISSUE THREAD

**Issue by jimmylle** [UCSB-CS56-Projects/cs56-android-games-pacman#3]
As it is, when PacMan and the Ghost collide, nothing happens. The game should end at that point.

**Comment by mbahia** [comment]
Approved 150 pts W16

**Comment by ntpincus** [comment]
150 points

**Comment by jimmylle** [comment]
This is resolved with these classes: [PlayerDeathException](https://github.com/UCSB-CS56-Projects/cs56-android-games-pacman/blob/master/app/src/main/java/com/example/jimmyle/pacmanandroid/PlayerDeathException.java), [FailedLevelActivity](https://github.com/UCSB-CS56-Projects/cs56-android-games-pacman/blob/master/app/src/main/java/com/example/jimmyle/pacmanandroid/FailedLevelActivity.java), and [Movement](https://github.com/UCSB-CS56-Projects/cs56-android-games-pacman/blob/master/app/src/main/java/com/example/jimmyle/pacmanandroid/Movement.java#L34).
