### ISSUE TITLE
No way to win game

### ISSUE THREAD

**Issue by jimmylle** [UCSB-CS56-Projects/cs56-android-games-pacman#4]
After collecting all the pellets, nothing happens. There should be an indicator that you've "Won" the level/game.

**Comment by mbahia** [comment]
Approved 200 pts W16

**Comment by ntpincus** [comment]
200 points

**Comment by jimmylle** [comment]
This is resolved with these classes: [DrawingView](https://github.com/UCSB-CS56-Projects/cs56-android-games-pacman/blob/62033aa0ee02fc237745ce8061b5807dcfc6e5c6/app/src/main/java/com/example/jimmyle/pacmanandroid/DrawingView.java) and [CompletedLevelActivity](https://github.com/UCSB-CS56-Projects/cs56-android-games-pacman/blob/master/app/src/main/java/com/example/jimmyle/pacmanandroid/CompletedLevelActivity.java).
