### ISSUE TITLE
Settings Page

### ISSUE THREAD

**Issue by ntpincus** [UCSB-CS56-Projects/cs56-android-games-pacman#6]
add content to the settings page (it does not exist)
consider an option to mute the exciting background music
200 points

**Comment by ntpincus** [comment]
100 points OK

**Comment by jimmylle** [comment]
This is resolved with [SettingsActivity](https://github.com/UCSB-CS56-Projects/cs56-android-games-pacman/blob/master/app/src/main/java/com/example/jimmyle/pacmanandroid/SettingsActivity.java).
