### ISSUE TITLE
Add mute/unmute

### ISSUE THREAD

**Issue by ntpincus** [UCSB-CS56-Projects/cs56-android-games-pacman#9]
Add a button that would mute/un-mute the sound while playing the game and without needing to go into a settings menu.

**Comment by ntpincus** [comment]
100 points

**Comment by ntpincus** [comment]
There is currently a bug when attempting to unmute the game in the settings page, if it was muted in the homescreen. This bug causes the app to crash.

**Comment by jimmylle** [comment]
F16 OK (100 pts)

**Comment by Tektonbuilds** [comment]
The mute button works
